export default {
  REQUEST_USERS: "REQUEST_USERS",
  RECEIVE_USERS: "RECEIVE_USERS",
  SELECT_USER: "SELECT_USER",
  ACTIVE_TAB: "ACTIVE_TAB",
  REQUEST_POSTS: "REQUEST_POSTS",
  RECEIVE_POSTS: "RECEIVE_POSTS",
  TOGGLE_POST: "TOGGLE_POST",
  REQUEST_COMMENTS: "REQUEST_COMMENTS",
  RECEIVE_COMMENTS: "RECEIVE_COMMENTS",
  REQUEST_ALBUMS: "REQUEST_ALBUMS",
  RECEIVE_ALBUMS: "RECEIVE_ALBUMS",
  REQUEST_PHOTOS: "REQUEST_PHOTOS",
  RECEIVE_PHOTOS: "RECEIVE_PHOTOS",
  TOGGLE_ALBUM: "TOGGLE_ALBUM",
  THUMBNAILS: "THUMBNAILS",
  REQUEST_TODOS: "REQUEST_TODOS",
  RECEIVE_TODOS: "RECEIVE_TODOS"
};
